### ISSUE TITLE
[SVG] element.className.split is not a function

### ISSUE THREAD

**Issue by baptistebriel** [dcamilleri/query-dom-components#2]
Yo!

J'essaye d'utiliser `query-dom-components` sur un SVG, et j'ai cette erreur:

`Uncaught TypeError: element.className.split is not a function` (ligne 22)

As-tu une idée de ce qui pourrait produire ca?

Thanks!

**Comment by dcamilleri** [comment]
Hey, 
I recreated the error on JSBin and fixed it: https://jsbin.com/mutiresivi/edit?html,js,console
It will be up on v0.0.7 ! 
Just run `npm install query-dom-components@0.0.7 --save` to update it :)
Let me know if you still get the error.

**Comment by baptistebriel** [comment]
👍
