### ISSUE TITLE
conflict with jQuery

### ISSUE THREAD

**Issue by baptistebriel** [dcamilleri/query-dom-components#4]
Hey Dorian,

I came across an issue today using `query-dom-components` and having `jQuery` defined in `window`;
I'm using the regular JavaScript `NodeList` afterwards, so passing a jQuery object returns an error.

I did a really quick patch as you can see in my fork, but it makes `hasJquery` to `false` by default if it's not previously specified in `options`.

I guess this is not the idea behind it so we could do the opposite:

``` javascript
var wantJquery = opts.jQuery || true;
var hasJquery = wantJquery && typeof jQuery !== 'undefined';
```

So we'll need to do this to prevent jQuery being used (even if it's loaded):

``` javascript
var DOM = query({ el: this.el, jQuery: false });
```

Let me know what you think!

**Comment by dcamilleri** [comment]
Hey @baptistebriel,
Can you post a fiddle or code example of what created the initial error ? 
Anyway, I understand the heart of the problem: the user should be able to have `jQuery` defined, and still have the opportunity to pass a `NodeList` to `queryDom`. 
I'll look into your fork in the next couple days !
Thanks,

**Comment by baptistebriel** [comment]
Hey @dcamilleri, any news on this? Did you had time to review my fork?
Let me know :)

**Comment by dcamilleri** [comment]
Hey @baptistebriel, sorry for being so long to answer . 
Your fork works well for this matter. Can you submit a PR ?

Thanks :)

**Comment by baptistebriel** [comment]
Sure, but it will probably cause conflicts if someone is using it along with jQuery and wants to update to the next version. I'll let you do what you think is best! Thanks! 👊
